# drag
-
  name: drag_coeff
  unit: dimensionless
  value: 0.141589419
-
  name: air_density
  unit: kg/m^3
  value: 1.225 
-
  name: frontal_area
  unit: m^2
  value: 1.268 

# rolling_resistance
-
  name: mu_rr
  unit: dimensionless
  value: 0.00175
-
  name: mu2_rr
  unit: h/km
  value: 0.0000311
-
  name: f_wheel_weight
  unit: kg
  value: 117.5633
-
  name: r_wheel_weight
  unit: kg
  value: 92.92334
-
  name: wheel_diameter
  unit: m
  value: 0.547624

# array
-
  name: num_cells
  unit: dimensionless
  value: 258 
-
  name: p_mpp
  unit: W
  value: 3.98 
-
  name: cell_efficiency
  unit: dimensionless
  value: 0.254
-
  name: latitude_deg
  unit: degree
  value: 30.2672      # Austin TX
-
  name: longitude_deg
  unit: degree
  value: -97.7431     # Austin TX
  
- name: total_array_energy
  value: 0
  unit: joule

# main
-
  name: timestep
  unit: minutes
  value: 30 
-
  name: raceday_len
  unit: hours
  value: 8
-
  name: velocity
  unit: mph
  value: 20
-
  name: total_energy
  unit: Wh
  value: 5240 
-
  name: weight
  unit: kg
  value: 328
-
  name: grav_accel
  unit: m/s^2
  value: 9.81
-
  name: start_ts
  unit: datetime
  value: 2026-07-01 09:00:00

#battery
#esr_loss_model
-
  name: cell_internal_impedance 
  unit: ohm
  value: 0.014
- 
  name: cells_in_series
  unit: dimensionless
  value: 32
-
  name: cells_in_parallel
  unit: dimensionless
  value: 9
-
  name: battery_voltage_nominal
  unit: volts
  value: 115.2
-
  name: battery_max_energy
  unit: Wh
  value: 5240

#LV draw constants
-
  name: enable_peak_draw
  unit: dimensionless
  value: 1
-
  name: vcu
  unit: amperes
  value: 0.750
-
  name: controls_leader
  unit: amperes
  value: 0.200
-
  name: horn
  unit: amperes
  value: 0.000
-
  name: horn_peak
  unit: amperes
  value: 4.000
-
  name: lighting
  unit: amperes
  value: 1.000
-
  name: lighting_peak
  unit: amperes
  value: 3.600
-
  name: pi_&_display
  unit: amperes
  value: 0.800
-
  name: pi_&_display_peak
  unit: amperes
  value: 0.850
-
  name: pedals
  unit: amperes
  value: 0.100
-
  name: camera_hub
  unit: amperes
  value: 0.050
-
  name: battery_box
  unit: amperes
  value: 1.800
-
  name: mppt_a
  unit: amperes
  value: 0.010
-
  name: mppt_b
  unit: amperes
  value: 0.010
-
  name: mppt_c
  unit: amperes
  value: 0.010
-
  name: motor_controller
  unit: amperes
  value: 1.000
-
  name: motor_controller_peak
  unit: amperes
  value: 2.200
-
  name: telemetry_leader
  unit: amperes
  value: 0.900
-
  name: telemetry_leader_peak
  unit: amperes
  value: 1.100
-
  name: pump
  unit: amperes
  value: 0.750
-
  name: pump_peak
  unit: amperes
  value: 1.250
-
  name: lv_voltage
  unit: volts
  value: 24
-
  name: DC_DC_converter
  unit: amperes
  value: 1.216    # accounts for two converters so indiv*2
-
  name: DC_DC_converter_peak
  unit: amperes
  value: 1.283

# motor_losses
# Temperature coefficient for copper resistance (α) - how much resistance increases per °C
-
  name: copper_temp_coefficient_alpha
  unit: 1/°C
  value: 0.00393

# Default motor loss model parameters
# k_H: Hysteresis loss coefficient (magnetic domain flipping in core)
# k_E: Eddy current loss coefficient (induced circulating currents in core)
# k_B1, k_B2: Bearing friction coefficients (mechanical friction)
# k_D: Air drag coefficient (windage from rotor spinning)
# k_SW: Commutation switching loss coefficient (brushless motor switching)
-
  name: motor_eta_C_default
  unit: dimensionless
  value: 0.97  # Controller efficiency
-
  name: motor_T_ref_default
  unit: °C
  value: 25.0  # Reference temperature for resistance measurements
-
  name: motor_T_operating_default
  unit: °C
  value: 70.0  # Operating temperature
-
  name: motor_k_H_default
  unit: W/rpm
  value: 0.0  # Hysteresis loss
-
  name: motor_k_E_default
  unit: W/rpm^2
  value: 0.0  # Eddy current loss
-
  name: motor_k_B1_default
  unit: N·m
  value: 0.0  # Bearing friction constant term
-
  name: motor_k_B2_default
  unit: N·m·min/rad
  value: 0.0  # Bearing friction speed-dependent term
-
  name: motor_k_D_default
  unit: W/rpm^3
  value: 0.0  # Air drag loss
-
  name: motor_k_SW_default
  unit: W/rpm
  value: 0.0  # Commutation switching loss
-
  name: motor_k_1_default
  unit: W/rpm
  value: 0.0
-
  name: motor_k_2_default
  unit: W/rpm^2
  value: 0.0
-
  name: motor_k_3_default
  unit: W/rpm^3
  value: 0.0

# Motor parameters - general configuration for the vehicle's motor
-
  name: motor_k_T
  unit: N·m/A
  value: 0.1910  # Torque constant
-
  name: motor_k_C
  unit: V·min/rad
  value: 0.020  # Back-EMF constant
-
  name: motor_k_S
  unit: N·m/A
  value: 0.1910  # Torque sensitivity (typically same as k_T)
-
  name: motor_R_A
  unit: ohm
  value: 0.0931  # Armature resistance
-
  name: motor_R_B
  unit: ohm
  value: 0.0233  # Brush/commutation resistance
-
  name: motor_eta_C
  unit: dimensionless
  value: 0.97  # Controller efficiency
