# drag
-
  name: drag_coeff
  unit: dimensionless
  value: 0.141589419
-
  name: air_density
  unit: kg/m^3
  value: 1.225 
-
  name: frontal_area
  unit: m^2
  value: 1.268 

# rolling_resistance
-
  name: mu_rr
  unit: dimensionless
  value: 0.00175
-
  name: mu2_rr
  unit: h/km
  value: 0.0000311

# array
-
  name: num_cells
  unit: dimensionless
  value: 258 
-
  name: p_mpp
  unit: W
  value: 3.98 
-
  name: cell_efficiency
  unit: dimensionless
  value: 0.254

# main
-
  name: timestep
  unit: minutes
  value: 30 
-
  name: raceday_len
  unit: hours
  value: 8
-
  name: velocity
  unit: km/h
  value: 50 
-
  name: total_energy
  unit: Wh
  value: 5240 
-
  name: weight
  unit: kg
  value: 328
-
  name: grav_accel
  unit: m/s^2
  value: 9.81
-
  name: start_ts
  unit: datetime
  value: 2026-07-01 09:00:00
  #battery
-
#esr_loss_model
  name: cell_internal_impedance 
  unit: ohm
  value: 0.014
- 
  name: cells_in_series
  unit: dimensionless
  value: 32
-
  name: cells_in_parallel
  unit: dimensionless
  value: 9
-
  name: instantaneous_current_draw
  unit: amps
  value: 225 
-
  name: battery_voltage_nominal
  unit: volts
  value: 115.2
-
  #LV draw constants
  name: lv_mode
  unit: dimensionless
  value: peak
-
  name: vcu
  unit: amps
  value: 0.750
-
  name: controls_leader
  unit: amps
  value: 0.200
-
  name: horn
  unit: amps
  value: 0.000
-
  name: horn_peak
  unit: amps
  value: 4.000
-
  name: lighting
  unit: amps
  value: 1.000
-
  name: lighting_peak
  unit: amps
  value: 3.600
-
  name: pi_&_display
  unit: amps
  value: 0.800
-
  name: pi_&_display_peak
  unit: amps
  value: 0.850
-
  name: pedals
  unit: amps
  value: 0.100
-
  name: camera_hub
  unit: amps
  value: 0.050
-
  name: battery_box
  unit: amps
  value: 1.800
-
  name: mppt_a
  unit: amps
  value: 0.010
-
  name: mppt_b
  unit: amps
  value: 0.010
-
  name: mppt_c
  unit: amps
  value: 0.010
-
  name: motor_controller
  unit: amps
  value: 1.000
-
  name: motor_controller_peak
  unit: amps
  value: 2.200
-
  name: telemtry_leader
  unit: amps
  value: 0.900
-
  name: telemtry_leader_peak
  unit: amps
  value: 1.100
-
  name: pump
  unit: amps
  value: 0.750
-
  name: pump_peak
  unit: amps
  value: 1.250