# drag
-
  name: drag_coeff
  unit: dimensionless
  value: 0.141589419
-
  name: air_density
  unit: kg/m^3
  value: 1.225 
-
  name: frontal_area
  unit: m^2
  value: 1.268 

# rolling_resistance
-
  name: mu_rr
  unit: dimensionless
  value: 0.00175
-
  name: mu2_rr
  unit: h/km
  value: 0.0000311
-
  name: f_wheel_weight
  unit: kg
  value: 117.5633
-
  name: r_wheel_weight
  unit: kg
  value: 92.92334

# array
-
  name: num_cells
  unit: dimensionless
  value: 258 
-
  name: p_mpp
  unit: W
  value: 3.98 
-
  name: cell_efficiency
  unit: dimensionless
  value: 0.254
-
 name: latitude_deg
 unit: degree
 value: 30.2672      # Austin TX

-
  name: longitude_deg
  unit: degree
  value: -97.7431     # Austin TX
  
- name: total_array_energy
  value: 0
  unit: joule
# main
-
  name: timestep
  unit: minutes
  value: 30 
-
  name: raceday_len
  unit: hours
  value: 8
-
  name: velocity
  unit: km/h
  value: 50 
-
  name: total_energy
  unit: Wh
  value: 5240 
-
  name: weight
  unit: kg
  value: 328
-
  name: grav_accel
  unit: m/s^2
  value: 9.81
-
  name: start_ts
  unit: datetime
  value: 2026-07-01 09:00:00
  
# lamination optics
-
  name: n_cover
  unit: dimensionless
  value: 1.5          # glass ~1.5, ETFE ~1.4

-
  name: t_cover
  unit: m
  value: 0.001        # cover thickness (replace w real)

-
  name: alpha_cover
  unit: 1/m
  value: 5            # absorption coeff (tune/replace)

-
  name: t_eva
  unit: m
  value: 0.0005       # EVA thickness (replace w real)

-
  name: alpha_eva
  unit: 1/m
  value: 20           # absorption coeff (tune/replace)

-
  name: tau_misc
  unit: dimensionless
  value: 0.98          # dirt/haze/gaps (tune)

-
  name: ar_gain
  unit: dimensionless
  value: 0.0           # set 0 unless you KNOW you have AR


#battery

#esr_loss_model
  name: cell_internal_impedance 
  unit: ohm
  value: 0.014
- 
  name: cells_in_series
  unit: dimensionless
  value: 32
-
  name: cells_in_parallel
  unit: dimensionless
  value: 9
-
  name: battery_voltage_nominal
  unit: volts
  value: 115.2