-
# drag
  name: drag_coeff
  unit: unitless
  value: 0.141589419
-
  name: density
  unit: air, kg/m^3
  value: 1.225 
-
  name: frontal_area
  unit: m^2
  value: 1.268 
-
# rolling_resistance
  name: normal_force
  unit: N
  value: 3218.71986 
-
  name: mu
  unit: unitless
  value: 0.3
-
  name: mu2
  unit: h/km
  value: 0.0011
-
# array
  name: num_cells
  unit: unitless
  value: 258 
-
  name: p_mpp
  unit: W
  value: 3.98 
-
# main
  name: timestep
  unit: minutes
  value: 30 
-
  name: velocity
  unit: km/h
  value: 50 
-
  name: total_power
  unit: Wh
  value: 4500 
-

